spring:
  application:
    name: config
  rabbitmq:
    host: 192.168.76.61
    port: 5672
  cloud:
    config:
      server:
        git:
          uri: http://192.168.76.61:8888/bjke/config-repo.git
          username: bjke
          password: sta6023728
eureka:
   client:
     serviceUrl:
       defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
   instance:
     prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"