spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_sell?characterEncoing=utf-8&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 890728
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/