eureka:
  client:
#    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8762