spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.76.61:3306/cloud_sell?characterEncoding=utf-8&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: iflytek
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/